### ISSUE TITLE
Duplicate sequence error

### ISSUE THREAD

**Issue by koakeson** [denglab/SeqSero2#1]
Hello,

I was attempting to run SeqSero2 on a paired end data set and received multiple "Duplicate sequence" errors and an "Your XML file was empty" error. 

Thanks,
Kelly O.

**Comment by ShaokangZhang** [comment]
Hi Kelly,

We understand that the SeqSero2 alpha-test version is still not stable and buggy. We are still working on it. Can you upload  your data for us to analyze? Or can you share us the data by Google drive to our account "denglabdatatransfer@gmail.com"?

Regards,
SeqSero Team
