### ISSUE TITLE
Is "SalmID" needed for all modes?

### ISSUE THREAD

**Issue by tseemann** [denglab/SeqSero2#11]
I don't have `SalmID` installed but it seemed to work on contigs ok?

**Comment by ShaokangZhang** [comment]
Hi Dr. Seemann,
The SalmID kmerized database was merged in SeqSero2 kmer database, so for contigs which only applied kmer mode, no SalmID needed. 
Other team members have fixed the rest of bugs, they will reply you soon about them.
Regards,
Shaokang
