### ISSUE TITLE
Inconsistent naming in output files

### ISSUE THREAD

**Issue by tseemann** [denglab/SeqSero2#12]
One uses capital `S` one uses lowercase `s` ?

```
SeqSero_log.txt
Seqsero_result.txt
```

**Comment by denglab** [comment]
Hi Tseemann,

We've fixed the bugs you found in the newest version of SeqSero2, which is updated to v1.0.1 now on Github.
Thank you very much for your suggestions and please feel free to let us know if you find any other problems.

Thanks,
Denglab
