### ISSUE TITLE
judge_subspecies split error

### ISSUE THREAD

**Issue by itsmeludo** [denglab/SeqSero2#13]
Hi, I have an error running from reads:

SeqSero2_package.py -t 2 -i x_R1.fastq.gz x_R2.fastq.gz
building database...
mapping...
check samtools version: 1.9
assembling...
blasting...

Traceback (most recent call last):
  File "/global/conda/envs/test/bin/SeqSero2_package.py", line 1423, in <module>
    main()
  File "/global/conda/envs/test/bin/SeqSero2_package.py", line 1271, in main
    subspecies=judge_subspecies(fnameA) #predict subspecies
  File "/global/conda/envs/test/bin/SeqSero2_package.py", line 1194, in judge_subspecies
    salm_species_scores=out.split("\n")[1].split("\t")[6:]

any idea what is happening?

best,
ludo

**Comment by denglab** [comment]
Hi Ludo,

We've updated our scripts. Could you please download the updated scripts and use the new "--check" option to check if you've had all the required dependencies installed? Could you check if SalmID was successfully installed?

Best,
Denglab

**Comment by itsmeludo** [comment]
Hi, you were right, althoug I install salmid, but a much newer version than your dependency.
Using bwa - /global/conda/envs/test/bin/bwa
Using samtools - /global/conda/envs/test/bin/samtools
Using blastn - /global/conda/envs/test/bin/blastn
Using fastq-dump - /global/conda/envs/test/bin/fastq-dump
Using spades.py - /global/conda/envs/test/bin/spades.py
Using bedtools - /global/conda/envs/test/bin/bedtools
ERROR: can not find SalmID.py in PATH

 I managed to pack SalmId 0.1.23, which doesn't include salmid.py like 0.11 does.
0.11 is over two years old though, is it normal to keep such an old version as a dependency of seqsero2? should we make a bug report on salmid issues?

I'll pack the right versions with conda and give a try.

**Comment by itsmeludo** [comment]
Hi!
I solved the dependency and packed both in conda.

for anyone interested, seqsero2 can be installed through conda by typing "conda install -c itsmeludo seqsero2"

as a note, both packages distribute a "version.py", so there is some clobbering happening. SalmID doesn't needs his to run, so if any version error is thrown by seqsero2, please just force the reinstall by typing "conda install -f seqsero2".

I hope the packaging helps :) Feel free to reference it in the documentation as here might not be the most intuitive place^^

Cheers for you work,
Best,

ludo
