### ISSUE TITLE
subspecies determination errors

### ISSUE THREAD

**Issue by retimme** [denglab/SeqSero2#27]
I'm working on a phylogeny of Salmonella subsp. arizonae and have located a few subsp. determination errors in SeqSero2:

SRR1175814 - SeqSero2 determines IIIa, but actually I
SRR4297729 - SeqSero2 determines IV, but actually IIIa
SRR3418287 - SeqSero2 determines II, but actually IIIa

Attaching the phylogeny, highlighting these tips.
[core_gene_FastTree_191112.pdf](https://github.com/denglab/SeqSero2/files/3897696/core_gene_FastTree_191112.pdf)

Thanks for the great work on this program!
-Ruth

**Comment by evolarjun** [comment]
Not sure what mode you're running SalmID in, but in the miniassembler mode I think the subspecies is determined by SalmID (https://github.com/hcdenbakker/SalmID).
