### ISSUE TITLE
Serotype Seftenberg Allele Mode

### ISSUE THREAD

**Issue by whottel** [denglab/SeqSero2#30]
I have been comparing some results of SeqSero to SeqSero2 and noticed a consistent discrepancy. All of my samples that were called "Senftenberg or Dessau*" in SeqSero are being called Westhampton by SeqSero2 in allele mode. I also tried out a serotype Seftenberg from the Sequence Read Archive (SRR7907800) and again SeqSero2 allele mode calls this Westhampton. However, when I try all of the same isolates in SeqSero2 k-mer mode then they are called as Seftenberg as expected. From your SeqSero2 article I gather that allele mode should be more accurate, but that does not appear to be the case for this particular sequence type.

**Comment by LSTUGA** [comment]
Thanks for your feedback. This problem has been fixed the latest SeqSero2 v1.1.0.
