### ISSUE TITLE
Fails to find antigens.pickle (seqsero2 installed through Conda) and recognizing output path

### ISSUE THREAD

**Issue by AleSR13** [denglab/SeqSero2#32]
I am running seqsero2 in a cond environment. I always encounter this error while running: FileNotFoundError: [Errno 2] No such file or directory: './conda/7750f859/database/antigens.pickle'

For some reason during the installation (at least in conda) the directory "database"  gets thrown inside another directory called "EGG_info". Manually moving "database" out from EGG_info solves the problem since the path to antigens.pickle would then be correct. However, when working inside a pipeline (snakemake)and automatically generating the environment, I cannot make that move and therefore the job fails. 

Another minor issue I ran into... seqsero2 does not seem to work if the output directory is a long path... it only works with one directory name (E.g. it works if the '-d Output_dir/' but not if '-d Output_dir/Sample_1/'). It is no big deal, but a bit annoying if I want to group all the results from many samples.

**Comment by LSTUGA** [comment]
Thanks for letting us know. We will try to fix these issues.
Could you please show us the command you used to install SeqSero2 through conda?

**Comment by AleSR13** [comment]
Sure! I just used: conda install -c bioconda seqsero2
At some point I also just cloned the GitHub repository and ran it from there... that worked just fine! It is only while installing through conda (bioconda). Thank you!!

**Comment by LSTUGA** [comment]
We just released a new SeqSero2 version 1.1.1, in which the problem of output directory you mentioned has been fixed.
Conda would sometimes install an older verison depending on the exsiting environment. It looks like v1.0.1 was installed in your case. Please have a try and see if you still have this problem with v1.1.1. To avoid this kind of version issue, I would suggest using ```conda install -c bioconda seqsero2=1.1.1``` to install the correct version.

**Comment by AleSR13** [comment]
I see... I installed the newest version and it does work. So... false alarm, sorry! Thank you for your help
