### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Chris091089** [denglab/SeqSero2#34]
Good afternoon and I tried to run seqsero2 from a docker container, however it appears that my fastq file does not exist and I have them in that folder.

the command used is docker run seqsero2 SeqSero2_package.py -p 10 -t 1 -i BB30 *

I hope you can help me.

 docker run seqsero2 SeqSero2_package.py -p 10 -t 1 -i BB30*
gzip: BB30_S1_R1.fastq.gz: No such file or directory

**Comment by LSTUGA** [comment]
May I ask whcih docker image for seqsero2 you are using?

Here is something you can try. Use -v flag to mount your local folder to the docker container. Just replace "YOUR_LOCAL_FOLDER" in the command below with the path to your data.
docker run -v /YOUR_LOCAL_FOLDER:/data seqsero2 SeqSero2_package.py -p 10 -t 2 -i BB30_S1_R1.fastq.gz BB30_S1_R2.fastq.gz

BTW, if you have paired-end reads, I would suggest using the "-t 2" option.

**Comment by Chris091089** [comment]
Thank you very much for the help I have solved my problem.
