### ISSUE TITLE
antigenic profile

### ISSUE THREAD

**Issue by Chris091089** [denglab/SeqSero2#44]
Good day

Why, in the case of the Muenches serovar, is the antigenic profile not being identified correctly?

According to the scheme described in the ANTIGENIC FORMULAE OF THE SALMONELLA SEROVARS document, the antigenic formula should be: 6.8:d:1.2, however, SeqSero2 only gives: 8:d:1.2

**Comment by denglab** [comment]
O8 serotypes that differ by only O6 have been shown to variably express O6 and are genetically indistinguishable (https://journals.asm.org/doi/10.1128/JCM.01676-12). They are combined in SeqSero2. Please refer to the SeqSero2 paper for details (https://journals.asm.org/doi/10.1128/AEM.01746-19?url_ver=Z39.88-2003&rfr_id=ori:rid:crossref.org&rfr_dat=cr_pub%20%200pubmed), especially Table S3. 



Table S3.   Summary of optimized interpretation of antigenic formula implemented in   SeqSero2
--
Antigen formula | SeqSero1 prediction | SeqSero2 prediction
8:k:1,5 | Haardt or Blockley | Blockley
8:r:1,5 | Hindmarsh or Bovismorbificans | Bovismorbificans
8:z10:e,n,x | Hadar or Istanbul | Hadar
8:l,v:1,2 | Pakistan or Litchfield | Litchfield
8:d:1,5 | Yovokome or Manhattan | Manhattan
8:d:1,2 | Virginia or Muenchen | Muenchen
8:e,h:1,2 | Newport or Bardo | Newport
